name: SpongeLava
version: 1.2.2-PREALPHA-SNAPSHOT
main: com.gmail.gogobebe2.spongelava.SpongeLava
description: Makes sponges act the same way with lava as it does with water.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com